openapi: 3.0.0
info:
  title: Eternal Dragons API
  description: Eternal Dragons REST API
  version: 1.0.0

servers:
  - url: http://localhost:4000/development
    description: Development server
  - url: https://dna.dragonspawn.xyz
    description: Staging server
  - url: https://api.eternaldragons.com
    description: Production server

paths:
  /dragon/{mint}:
    get:
      summary: Returns a dragon
      description: Returns a dragon
      parameters:
        - name: mint
          in: path
          required: true
          description: Mint address of the dragon
          schema:
            type: string
      responses:
        "200":
          description: A JSON of a dragon
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dragon"

  /dragons/{address}:
    get:
      summary: Returns a list of user dragons
      description: Returns a list of user dragons
      parameters:
        - name: address
          in: path
          required: true
          description: User solana wallet address
          schema:
            type: string
      responses:
        "200":
          description: A JSON array of user dragons
          content:
            application/json:
              schema:
                type: array
                description: A JSON array of user dragons
                items:
                  $ref: "#/components/schemas/Dragon"

  /ranks:
    get:
      summary: Returns a list of dragons rarity scores
      description: Returns a list of dragons rarity scores
      responses:
        "200":
          description: A JSON array of dragons rarity scores
          content:
            application/json:
              schema:
                type: array
                description: A JSON array of dragons rarity scores
                items:
                  $ref: "#/components/schemas/Rank"

components:
  schemas:
    Dragon:
      type: object
      properties:
        affinity:
          type: string
          description: Affinity of the dragon
        attributes:
          type: array
          description: Dragon atributes
          items:
            type: object
            properties:
              trait_type:
                type: string
              value:
                type: string
        canReveal:
          type: boolean
          description: Can dragon be revealed
        class:
          type: string
          description: Class of the dragon
        collection:
          type: array
          description: Collection to which the dragon belongs to
          items:
            type: object
            properties:
              name:
                type: string
              family:
                type: string
        description:
          type: string
          description: Description of the dragon
        image:
          type: string
          description: Image URL of the dragon
        mint:
          type: string
          description: Mint address of the dragon
        name:
          type: string
          description: Name of the dragon
        properties:
          type: object
          description: List of dragon properties
          properties:
            files:
              type: array
              description: List of dragons URIs
              items:
                type: object
                properties:
                  uri:
                    type: string
            category:
              type: number
        revealCountdownMs:
          type: number
          description: Counter in ms after which user can reveal dragon (optional).
        score:
          type: object
          description: Dragon rarity scores
          properties:
            visual:
              type: number
            power:
              type: number
            gene:
              type: number
            total:
              type: number
            tier:
              type: number
            label:
              type: string
        seller_fee_basis_points:
          type: number
          description: Percentage of the seller fee
        status:
          type: number
          description: Status of the request that load the dragon
        symbol:
          type: string
          description: Symbol of the dragon
    Rank:
      type: object
      properties:
        affinity:
          type: string
          description: Affinity of the dragon
        class:
          type: string
          description: Class of the dragon
        gene:
          type: number
          description: Gene score of the dragon
        id:
          type: string
          description: Mint address of the dragon
        label:
          type: string
          description: Rarity label of the dragon
        name:
          type: string
          description: Name of the dragon
        power:
          type: number
          description: Power score of the dragon
        total:
          type: number
          description: Total score of the dragon
        visual:
          type: number
          description: Visual score of the dragon
